@extends('new_frontend.layouts.app')
@section('content')
   @include('new_frontend.includes.header')
      <div class="layout">
      	@include('new_frontend.includes.sidebar')
      	<div class="content">
            <div class="container">
               <div class="row disclaimer_sec">
                  <h2>Terms and conditions forming part of the Application Form for Registration of Unit</h2>
                  <ul class="tc tc2">
                     <li>This Application Form for registration for provisional allotment is letter of intent expressing the interest/intent of the Applicant to Purchase an Unit in the Project. This Form does not, by itself, create any rights, title and interest in favour of the Applicant. The Allotment shall be final and binding upon the company only after the execution of Unit Buyer Agreement. Detailed Terms &amp; Conditions shall form part of the Flat Buyer Agreement which the applicant shall execute as and when required by the company in the company’s standard format which has been thoroughly read and clearly understood by the Applicant. Such detailed Unit Buyer Agreement shall supersede the terms of this Application Form.</li>
                     <li>Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure.</li>
                     <li>The Registration for booking of Unit is at the sole discretion of the Company. Company can reject any application without assigning any reason.</li>
                     <li>The Intending applicant(s) has fully satisfied him/her self about the ownership, legal document, and physical location of the proposed Unit at the time of application and accordingly no objections, investigation or questions will be raised by the applicant in this respect at any time in future.</li>
                     <li>Due to any reason, if the company is unable to offer registration for booking/ allotment of the Unit to the applicant than it shall provide two options to the applicant i.e. (a). The Applicant (s) may apply for an alternative property developed by the company or, (b). The company shall refund the amount deposited with simple interest @ 9% PA.</li>
                     <li>As per the availability of the Unit company may offer for allotment of the unit in favour of intending applicant.</li>
                     <li>That on receipt of information of registration for booking/ allotment of the Unit the applicant shall be abide to make payment as per Payment Plan (enclosed) and be bound by the terms and conditions of this application form and as per company’s standard format of agreement contents of which have been read and understood by the applicant.</li>
                     <li>That applicant is entitled only once to get the name of his/ her spouse/ children/ parents substituted in his/ her place in the record of the company, who may in its sole discretion permit the same on such condition as it may deem fit.</li>
                     <li>Any cancellation of booking after registration by the applicant is subject to cancellation charges @ 20% of the total value of the Unit. These charges would be deducted from the amount deposited by the applicant.</li>
                     <li>That the Applicant(s) on being Non-Resident Indian/ Foreign National Buyer shall be responsible for the fulfillment of it's Obligations in the Foreign Exchange Management Act, 1999, instruction/directions issued by Reserve Bank of India and other prevailing applicable laws, rules notifications including that for the remittance of payment(s) and obtaining permission as prescribed by law for acquisition of immovable property in India.</li>
                     <li>In case of joint application, if Applicant(s) claims for cancellation, the Company will refund payment in favour of 1st Applicant after deduction of cancellation charges and all the Applicants hereby accord their consent for the same.</li>
                     <li>The applicant shall get his/ her complete address registered with the Company at the time of applying for registration and it shall be his/her responsibility to inform the Company by Registered AD letter about all subsequent changes, if any in his/ her address, failing which all demand notices and letters will be posted at the first applicant registered address and it will be deemed to have been received by applicant(s). The applicant shall be responsible for any default in payment and/ or other consequences that might occur there from.</li>
                     <li>If the intending allottee(s) fails to pay successive installments(s) within the prescribed time then interest shall be payable as: - (A). Up to one month from the due date of unpaid installment 18% RA. of the due amount. (B)After one month onwards from the due date of unpaid installment 24% PA. of the due amount. (C). After three months from of due date of unpaid installment Company will have right to cancel the registration which is subject to cancellation charges @ 20% of the value of the Unit.</li>
                     <li>
                        MAHARERA’s as applicable 
                        <span>a) Rera No. P52900019883 for Tower No. A, D and G.</span>
                        <span> b) Rera No. P52900021725 for Tower No. B, E and H.</span>
                     </li>
                     <li>In case intending Applicant/Allottee wants to avail for a loan facility from his/ her employer or financing bodies to facilitate the purchase of the unit applied for the company shall facilitate the process subject to the following: - (A). The terms of the Financing Agency shall exclusively be binding and applicable upon the applicant only. (B). The responsibility of getting the loan sanctioned and disbursed as per the Company payment plan/schedule shall rest exclusively on the Applicant/Allottee, In the event of the loan not been sanctioned or the disbursement getting delayed, then the payment including interest payable to the Company as per payment plan/schedule shall be ensured by the applicant/ allottee.</li>
                     <li>If any third party makes payment/ remittance on behalf of the applicant(s). He/ She shall have no any claim on the Company and the Company shall not be responsible of such transaction of third party.</li>
                     <li>In case of acquisition of land by government or for the execution of order passed by any competent court the Company shall refund the amount deposited by the applicant without interest.</li>
                     <li>The Company shall not be responsible or liable for delay in allotment of Unit, If such performance is prevented, delayed or hindered by any reasons which is beyond reasonable control of company for example if any competent authority(ies) refuses, delays, withholds denies the grant of necessary approvals for any reason whatsoever, force majeure events, Act of God, Govt./ Court order, change in laws, Dispute, War, Action by Military authorities or any other cause/reasons.</li>
                     <li>Company reserves the right to change any design layout area specification/ facilities and amenities of the proposed project without prior notice and information. The Brochure/ map is for illustration purpose only and it cannot be treated as legal document.</li>
                     <li>That after completion of the Unit and receipt of fully consideration and other charges, if any, payable by the Applicant(s), Sale Deed shall be executed in favour of the Applicant (s) on the format provided by the Company. All expenses towards execution of Sale Deed/ registration shall be borne by the AppIicant(s). That the AppIicant(s) undertakes to remain present before the registering Authority at the time of Registration of the Sale Deed.</li>
                     <li>The intending allottee(s) shall make payment of all the amenities and services before possession/ registry whichever is earlier and thereafter the intending allottee shall be liable to pay regular expenses i.e. maintenance charges, development charges and other necessary charges etc. to the company society (as the case may be) for proper development and maintenance of the amenities and facilities.</li>
                     <li>No legal proceedings can be initiated by the applicants(s)/ allottee(s) against the company on the basis of this application form.</li>
                     <li>The company has sole right to incorporate more terms and conditions for smooth functioning , construction of the project or to effectuate any statutory rules and regulations. Applicants shall follow all the rules and regulations related to Registrar Office for timely execution of BBA / ATS, he shall be sole responsible for any delay in execution of BBA / ATS and relevant penalty if any.</li>
                     <li>That legal heirs and representatives of the applicant(s) will also be bound in all respect of the terms and conditions of this application form.</li>
                     <li>The payment shall be accepted only through A/c payee Cheque, Bank Draft, Bank Cheque or through NEFT/ RTGS drawn in favour of <strong>M/s Eejak Holdings Pvt. Ltd.</strong></li>
                     <li>Any dispute of difference amongst the Applicant/Allottee(s) and the Company shall be resolve through arbitrator in term of the Arbitration and Conciliation Act, 1996 and statutory modifications thereof. The venue of the arbitration shall be at Panaji - Goa only. Subject to the aforesaid, the Courts at Maharashtra shall have exclusive jurisdiction to entertain the dispute between the parties hereto.</li>
                     <li>Applicant have to maintain all correspondence / Communication to Yog Villas, <strong>M/s Eejak Holdings Pvt. Ltd.</strong> , 305, Gera Imperium Grand, Patto Plaza, Panaji, Goa 403001 (INDIA) or email at "info@axisecorp.com" only.</li>
                  </ul>
               </div>
            </div>
         @include('new_frontend.includes.footer')
@endsection